/// Well-Known Types from Protocol Buffers.
///
/// These types are distributed with the Protocol Buffers compiler, and are
/// imported by the files generated by the compiler plugins.
///
/// This library is for using in curated Dart code, while the individual
/// type libraries are useful for the generated sources.
library;

export 'google/protobuf/any.pb.dart';
export 'google/protobuf/api.pb.dart';
export 'google/protobuf/descriptor.pb.dart';
export 'google/protobuf/duration.pb.dart';
export 'google/protobuf/empty.pb.dart';
export 'google/protobuf/field_mask.pb.dart';
export 'google/protobuf/source_context.pb.dart';
export 'google/protobuf/struct.pb.dart';
export 'google/protobuf/timestamp.pb.dart';
export 'google/protobuf/type.pb.dart';
export 'google/protobuf/wrappers.pb.dart';
